[tool.poetry]
name = "template"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "*"
pydocstyle = "*"
mypy = "*"
pre-commit = "*"
isort = "*"
black = { version="*", allow-prereleases = true }

[tool.black]
line-length = 100
target-version = ["py38"]
exclude = '''
(
  \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | dist
)
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
